# ============================================================
# APPLICATION
# ============================================================
spring.application.name=sb-ecom
server.port=5000

# ============================================================
# DATASOURCE (PostgreSQL - LOCAL)
# ============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=Bunny@0718

# ============================================================
# JPA / HIBERNATE
# ============================================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ============================================================
# JWT SECURITY
# ============================================================
app.jwt.secret=mySecretKey123912738ujeachdjhbakjojnuihqjsdckjsdchfcgfxjfcghcfgvf
app.jwt.expiration=86400000
spring.ecom.app.jwtCookieName=springBootEcom

# ============================================================
# FILE STORAGE
# ============================================================
project.image=images/

frontend.url=http://localhost:5173/
image.base.url=http://localhost:5000/images