# ============================================================
# APPLICATION
# ============================================================
spring.application.name=sb-ecom
server.port=5000

# ============================================================
# DATASOURCE values injected by Elastic Beanstalk env vars
# ============================================================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ============================================================
# JPA / HIBERNATE
# ============================================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ============================================================
# JWT SECURITY
# ============================================================
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000
spring.ecom.app.jwtCookieName=springBootEcom

# ============================================================
# FILE STORAGE
# ============================================================
project.image=images/
